name: dart_otp
description: dart_otp is a dart package to generate and verify one-time passwords.
version: 1.4.0
author: Gin <gin.lance.inside@hotmail.com>

homepage: https://github.com/BrunoMiguens/dart_otp

environment:
  sdk: ">=1.13.0 <3.0.0"

dependencies:
  crypto: ^3.0.0
  base32: ^1.0.1

dev_dependencies:
  test: ^1.11.1
  test_coverage: ^0.5.0